package com.group50.paymentservice.util;

import com.group50.paymentservice.model.Payment;
import com.group50.paymentservice.repository.PaymentRepository;
import com.opencsv.CSVReader;
import org.springframework.boot.CommandLineRunner;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Component;

import java.io.InputStreamReader;
import java.time.Instant;
import java.util.List;

@Component
public class CsvSeeder implements CommandLineRunner {

    private final PaymentRepository repo;

    public CsvSeeder(PaymentRepository repo) {
        this.repo = repo;
    }

    @Override
    public void run(String... args) throws Exception {
        if (repo.count() > 0) return;

        ClassPathResource resource = new ClassPathResource("/app/rhfd_payments.csv");
        try (CSVReader reader = new CSVReader(new InputStreamReader(resource.getInputStream()))) {
            List<String[]> rows = reader.readAll();

            for (int i = 1; i < rows.size(); i++) {
                String[] r = rows.get(i);
                Instant createdAt;
                try {
                    createdAt = Instant.parse(r[6]);
                } catch (Exception ex) {
                    createdAt = Instant.now();
                }

                Payment payment = new Payment(
                        null,                    // id → autogenerated by JPA
                        r[0],                    // paymentId
                        r[1],                    // tripId
                        Double.parseDouble(r[2]),// amount
                        r[3],                    // method
                        r[4],                    // status
                        r[5],                    // reference
                        createdAt                // createdAt
                );

                repo.save(payment);
            }

            System.out.println("Seeded " + (rows.size() - 1) + " payments into PostgreSQL.");
        } catch (Exception e) {
            System.out.println(" CSV seeding failed: " + e.getMessage());
        }
    }
}
